export const INCREMENT_STARTED = 'INCREMENT_STARTED';
export type INCREMENT_STARTED = typeof INCREMENT_STARTED;
export const INCREMENT = 'INCREMENT';
export type INCREMENT = typeof INCREMENT;
export const INCREMENT_CANCELED = 'INCREMENT_CANCELED';
export type INCREMENT_CANCELED = typeof INCREMENT_CANCELED;
